<?php

namespace frontend\modules\v1\controllers;

use frontend\modules\v1\models\TaskSearch;
use tasktracker\entities\task\Tasks;
use yii\filters\auth\HttpBearerAuth;
use yii\rest\ActiveController;
use yii\web\Request;

class TaskController extends ActiveController
{
    public $modelClass = Tasks::class;
    private $request;

    public function __construct($id, $module, Request $request, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->request = $request;

    }


    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::class,
        ];
        return $behaviors;
    }

    public function actions()
    {
        $actions = parent::actions();
        unset($actions['index']);
        return $actions; // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $searchModel = new TaskSearch();
        return $searchModel->search($this->request->get());

//        $query = Tasks::find();

//        return new ActiveDataProvider([
//            'query' => $query
//        ]);
    }
}